- hosts: windows

  tasks:
    - name: test raw module with ipconfig
      hosts: windows
      tasks:
        - name: run ipconfig
          win_command: ipconfig
          register: ipconfig
        - debug: var=ipconfig