- name: test script module
  hosts: windows
  tasks:

    - debug:
        msg: "{{ ansible_facts }}"


- name: test script module
  hosts: windows
  tasks:
    - name: run test script
      script: files/test_script.ps1
      register: psoutput

    - debug:
        msg: "{{ psoutput.stdout }}"