- name: test script module
  hosts: windows
  tasks:

    - name: run test script
      script: files/test_script.ps1
      register: psoutput

    - debug:
        msg: "{{ psoutput.stdout }}"

    - name: run test script
      win_shell: Get-WmiObject win32_operatingsystem | select csname, @{LABEL=’LastBootUpTime’;EXPRESSION={$_.ConverttoDateTime($_.lastbootuptime)}} | ConvertTo-Json
      register: uptime

    - debug:
        msg: "{{ uptime.stdout }}"
