---
- hosts: cloudx

  tasks:
    - name: reachability test
      iosxr_command:
        provider: "{{ iosxrcli }}"
        commands: ping ipv4 192.168.255.1 vrf VPN_DICT
      register: ping_results
      ignore_errors: yes
 
    - name: view output
      debug:
        msg: "{{ ping_results.stdout[3] }}"


- hosts: localhost

  tasks:
    - name: record ping results to file 
      lineinfile:
        path: ./reports/rtr1-azure.csv 
        state: present
        line: '{{ ping_results.stdout[3] }}'
    
       