---
- hosts: cloudx

  tasks:
    - name: reachability test
      iosxr_command:
        commands: ping ipv4 192.168.255.1 vrf VPN_DICT
        register: ping_results
        ignore_errors: yes
 
    - name: view output
      debug:
        msg: "{{ ping_results }}"
   