---
- hosts: cloudx

  tasks:
    - name: show clock 
      iosxr_command:
        provider: "{{ iosxrcli }}"
        commands: show clock
      register: time

    - name: ios_ping
      ios_ping:
        provider: "{{ iosxrcli }}"
        dest: '{{ item }}'
      with_items:
        - 192.168.200.2 vrf VPN_001_TBS
      register: ping_results
      ignore_errors: yes

    - name: view output
      debug:
        msg: "{{ ping_results.results[0].packet_loss }}"

    - set_fact: rtr1_az={{ ping_results.results[0] }}   


    - name: record ping results rtr1 azure 
      lineinfile:
        path: ./reports/rtr1-azure.csv 
        state: present
        create: yes
        line: '{{ time.stdout }},rtr1,azure,{{ rtr1_az.packet_loss }},{{ rtr1_az.rtt.avg }},{{ rtr1_az.rtt.min }},{{ rtr1_az.rtt.max }}'
      delegate_to: localhost
