---
- hosts: cloudx

  tasks:
    - name: show clock 
      iosxr_command:
        provider: "{{ iosxrcli }}"
        commands: show clock
      register: time

    - name: ios_ping
      ios_ping:
        provider: "{{ iosxrcli }}"
        dest: '{{ item }}'
      with_items:
        - 192.168.255.1 vrf VPN_DICT
        - 172.16.10.2 vrf VPN_DICT 
      register: ping_results
      ignore_errors: yes

    - name: view output
      debug:
        msg: "{{ ping_results.results[0].packet_loss }}"

    - set_fact: rtr1_az={{ ping_results.results[0] }}   
    - set_fact: rtr1_tel={{ ping_results.results[1] }}


    - name: record ping results rtr1 azure 
      lineinfile:
        path: ./reports/rtr1-azure.csv 
        state: present
        create: yes
        line: '{{ time.stdout }},rtr1,azure,{{ rtr1_az.packet_loss }},{{ rtr1_az.rtt.avg }},{{ rtr1_az.rtt.min }},{{ rtr1_az.rtt.max }}'
      delegate_to: localhost 

    - name: record ping results rtr1 telus
      lineinfile:
        path: ./reports/rtr1-telus.csv
        state: present
        create: yes
        line: '{{ time.stdout }},rtr1,telus,{{ rtr1_tel.packet_loss }},{{ rtr1_tel.rtt.avg }},{{ rtr1_tel.rtt.min }},{{ rtr1_tel.rtt.max }}'
      delegate_to: localhost
