- hosts: dc-core

  tasks:
    - name: create dc core configuration file
      template:
        src: "./templates/configuration/dc-core.j2"
        dest: './reports/configuration/{{inventory_hostname}}.cfg'
