---
- hosts: dc-core

  tasks:
    - name: gather nxos interfaces facts
      nxos_facts:
        gather_subset: interfaces
        provider: "{{ nxosapi }}"
      register: gather_nxos_interfaces

    - set_fact: int_facts={{ gather_nxos_interfaces.ansible_facts.ansible_net_interfaces }}
    
    - name: view output
      debug:
        msg: "{{ int_facts }}"
   
    - name: save output results per device
      template:
        src: "./templates/interface-status/interface-status.j2"
        dest: "./reports/interface-status/devices/{{inventory_hostname}}-nxos-interface-report.csv"

- hosts: localhost

  tasks:
  
    - name: create combinned report
      assemble:
        src: "./reports/interface-status/devices"
        dest: "./reports/interface-status/nxos-interface-report.csv"