---
- name: enable extras repo
  yum:
    name: epel-release
    state: present

- name: install xrdp
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - xrdp
    - tigervnc-server

- name: start and enable xrdp service
  service:
    name: xrdp
    enabled: yes
    state: started

