---
- name: enable extras repo
  yum:
    name: epel-release
    state: present

- name: install administration tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools

- name: install python tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python-devel
    - gcc

- name: install ansible windows kerberos dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - krb5-devel
    - krb5-libs
    - krb5-workstation


- name: install python winrm
  pip:
    name: pywinrm>=0.2.2

- name: install python-kerberos
  pip:
    name: pywinrm[kerberos]

- name: install ansible microsoft azure dependencies
  pip:
    name: ansible[azure]

- name: Copy Kerberos reaml configuration file
  template:
    src: kerberos-reamls.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  notify: reboot host