- hosts: localhost
  
  tasks:
    - name: install administration tools
      yum:
        name: {{ item }}
        state: present
      with_items:
        - net-tools
  
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      notify: reboot host
  
  handlers:
    - name: reboot host
      command: /sbin/reboot