
- hosts: gitlab

  vars_files:
    - vars/gitlab.yml
  
#  vars_prompt:
#    - name: ansible_user
#      prompt: "Enter ansible user"
#      private: no
#
#    - name: ansible_password
#      prompt: "Enter ansible password"
#      private: yes

  
  tasks:
  - include_role: 
       name: gitlab
