- hosts: enterprise

  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      notify: reboot host
  
  handlers:
    - name: reboot host
      command: /sbin/reboot